-- Create votes table for macro ratings
-- Run this SQL in Supabase dashboard: https://supabase.com/dashboard/project

CREATE TABLE IF NOT EXISTS votes (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  macro_file_url TEXT UNIQUE NOT NULL,
  up_count INT DEFAULT 0,
  down_count INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE votes ENABLE ROW LEVEL SECURITY;

-- Create policy to allow anyone to read votes
CREATE POLICY "READ votes" ON votes
  FOR SELECT USING (true);

-- Create policy to allow anyone to insert/update votes
CREATE POLICY "INSERT/UPDATE votes" ON votes
  FOR INSERT WITH CHECK (true);

CREATE POLICY "UPSERT votes" ON votes
  FOR UPDATE USING (true) WITH CHECK (true);

-- Create index on macro_file_url for faster queries
CREATE INDEX idx_votes_macro_file_url ON votes(macro_file_url);

-- Grant permissions to authenticated and anonymous users
GRANT SELECT, INSERT, UPDATE ON votes TO authenticated, anon;
